### PR TITLE
Add integration tests and CI

### LINKED ISSUE #5: Integration test(s)

### PR DESCRIPTION
**Pull request by dbrgn**
Fixes #5.

### CODE REVIEW

**Comment by dbrgn** [comment]
@hfiguiere tests currently fail because libopenraw-3 is not available on Ubuntu. Do your bindings work with libopenraw-1 as well?

The libopenraw-dev package provides a pkg-config file: https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libopenraw-dev_0.1.2-0.2_amd64.deb.html

**Comment by hfiguiere** [comment]
No they don't. There have been API changes.

**Comment by dbrgn** [comment]
Ok, too bad, then the bindings won't work for any currently published distro that doesn't do rolling release (Ubuntu, Debian, Fedora...). But I guess that's acceptable. I'll add a note to the README.

**Comment by dbrgn** [comment]
Maybe Rust allows static linking against C libs, so that libopenraw could be vendored in for systems that haven't installed it systemwide?

**Comment by hfiguiere** [comment]
There could be an option to build the bindings with a static version of the lib, but this is not on top of my list.

**Pull request merged**
